

const NUMDATE_EVGY_MON = "1SunToMon"
const NUMDATE_EVGY_TUE = "2MonToTue"
const NUMDATE_EVGY_WED = "3TueToWed"
const NUMDATE_EVGY_THR = "4WedToThr"
const NUMDATE_EVGY_FRI = "5ThrToFri"
const NUMDATE_EVGY_SUN = "7SunToMon"

const NUMDATE_DAY_MON = "1Mon"
const NUMDATE_DAY_TUE = "2Tue"
const NUMDATE_DAY_WED = "3Wed"
const NUMDATE_DAY_THR = "4Thr"
const NUMDATE_DAY_FRI = "5Fri"

const NUMDATE_WKND_SAT = "6Sat"
const NUMDATE_WKND_SUN = "7Sun"

const ENDOFWEEK = "EndOfWeek"



module.exports = {

  NUMDATE_EVGY_MON : NUMDATE_EVGY_MON,
  NUMDATE_EVGY_TUE : NUMDATE_EVGY_TUE,
  NUMDATE_EVGY_WED : NUMDATE_EVGY_WED,
  NUMDATE_EVGY_THR : NUMDATE_EVGY_THR,
  NUMDATE_EVGY_FRI : NUMDATE_EVGY_FRI,

  NUMDATE_EVGY_SUN : NUMDATE_EVGY_SUN,

  NUMDATE_DAY_MON : NUMDATE_DAY_MON ,  
  NUMDATE_DAY_TUE : NUMDATE_DAY_TUE ,  
  NUMDATE_DAY_WED : NUMDATE_DAY_WED ,  
  NUMDATE_DAY_THR : NUMDATE_DAY_THR ,  
  NUMDATE_DAY_FRI : NUMDATE_DAY_FRI ,  

  NUMDATE_WKND_SAT : NUMDATE_WKND_SAT, 
  NUMDATE_WKND_SUN : NUMDATE_WKND_SUN,

  ENDOFWEEK : ENDOFWEEK

};