module.exports = {
  SCDBATCH1 : "SCDBATCH1",
  SCDBATCH2 : "SCDBATCH2",
  SCDBATCH3 : "SCDBATCH3",
  SCDBATCH4 : "SCDBATCH4",
  SCDBATCH5 : "SCDBATCH5",
  SCDBATCH6 : "SCDBATCH6",
  SCDBATCH7 : "SCDBATCH7",

  BATCH1 : "BATCH1",
  BATCH2 : "BATCH2",
  TEMP : "TEMP"
}