[PCOMM SCRIPT HEADER]

LANGUAGE=VBSCRIPT

DESCRIPTION=

[PCOMM SCRIPT SOURCE]

OPTION EXPLICIT

autECLSession.SetConnectionByName(ThisSessionName)

 

 

 

 

REM TONIGHTS's OUTQ is: /OUTQ3

 

 

REM This line calls the macro subroutine

subSub1_

 

sub subSub1_()

   autECLSession.autECLOIA.WaitForAppAvailable

 

 

  

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "[pf7]"

  

   autECLSession.autECLPS.WaitForAttrib 18,6,"00","3c",3,10000

 

   autECLSession.autECLPS.WaitForCursor 18,7,10000

 

   autECLSession.autECLOIA.WaitForAppAvailable

 

   ' ========== ====================== ====================== =============== ============

 

 

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "QSYS/MOVSPLFBRM OPTION(*MOVE) TOOUTQ(PDSYLIB000/OUTQ3) FROMOUTQ(PDSYLIB000/QPJOBLOG1) FILE(QPJOBLOG) JOB(HOENDP000) SLTCRTDATE(080221)"

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "[enter]"

  

   autECLSession.autECLPS.WaitForAttrib 18,6,"00","3c",3,10000

 

   autECLSession.autECLPS.WaitForCursor 18,7,10000

 

   autECLSession.autECLOIA.WaitForAppAvailable

 

 

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "QSYS/MOVSPLFBRM OPTION(*MOVE) TOOUTQ(PDSYLIB020/OUTQ3) FROMOUTQ(PDSYLIB020/QPJOBLOG1) FILE(QPJOBLOG) JOB(DCENDP020) SLTCRTDATE(080221)"

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "[enter]"

  

   autECLSession.autECLPS.WaitForAttrib 18,6,"00","3c",3,10000

 

   autECLSession.autECLPS.WaitForCursor 18,7,10000

 

   autECLSession.autECLOIA.WaitForAppAvailable

 

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "QSYS/MOVSPLFBRM OPTION(*MOVE) TOOUTQ(PDSYLIB022/OUTQ3) FROMOUTQ(PDSYLIB022/QPJOBLOG1) FILE(QPJOBLOG) JOB(DCENDP022) SLTCRTDATE(080221)"

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "[enter]"

  

   autECLSession.autECLPS.WaitForAttrib 18,6,"00","3c",3,10000

 

   autECLSession.autECLPS.WaitForCursor 18,7,10000

 

   autECLSession.autECLOIA.WaitForAppAvailable

 

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "QSYS/MOVSPLFBRM OPTION(*MOVE) TOOUTQ(PDSYLIB079/OUTQ3) FROMOUTQ(PDSYLIB079/QPJOBLOG1) FILE(QPJOBLOG) JOB(DCENDP079) SLTCRTDATE(080221)"

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "[enter]"

  

   autECLSession.autECLPS.WaitForAttrib 18,6,"00","3c",3,10000

 

   autECLSession.autECLPS.WaitForCursor 18,7,10000

 

   autECLSession.autECLOIA.WaitForAppAvailable

 

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "QSYS/MOVSPLFBRM OPTION(*MOVE) TOOUTQ(PDSYLIB110/OUTQ3) FROMOUTQ(PDSYLIB110/QPJOBLOG1) FILE(QPJOBLOG) JOB(DCENDP110) SLTCRTDATE(080221)"

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "[enter]"

  

   autECLSession.autECLPS.WaitForAttrib 18,6,"00","3c",3,10000

 

   autECLSession.autECLPS.WaitForCursor 18,7,10000

 

   autECLSession.autECLOIA.WaitForAppAvailable        

 

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "QSYS/MOVSPLFBRM OPTION(*MOVE) TOOUTQ(PDSYLIB172/OUTQ3) FROMOUTQ(PDSYLIB172/QPJOBLOG1) FILE(QPJOBLOG) JOB(DCENDP172) SLTCRTDATE(080221)"

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "[enter]"

  

   autECLSession.autECLPS.WaitForAttrib 18,6,"00","3c",3,10000

 

   autECLSession.autECLPS.WaitForCursor 18,7,10000

 

   autECLSession.autECLOIA.WaitForAppAvailable        

 

 

 

   ' ========== ====================== ====================== =============== ============           

 

                                

   autECLSession.autECLOIA.WaitForInputReady

   autECLSession.autECLPS.SendKeys "DONE"

 

 

 

end sub